services:
#Base de datos
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
#Api-backend de comunicacion con la base de datos, frontend y servicio de excel
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: npm run dev
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH_CALLBACK_URL: ${OAUTH_CALLBACK_URL}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./api:/app
      - /app/node_modules
#Frontend de comunicacion con el usuario y el backend
  web:
    build: ./web
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5174:5173"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
#Servicio de excel para comunicacion con el backend y generacion de archivos excel
  excel:
    build: ./excel-service
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_URL: ${API_URL}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
